# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0003_auto_20170826_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'')),
                ('html', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
