# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0004_auto_20170826_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='html',
            field=models.FileField(upload_to='media/html'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='picture',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
