# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0005_auto_20170827_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maps',
        ),
        migrations.RenameField(
            model_name='fcm',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='fcm',
            name='map_file',
        ),
        migrations.AddField(
            model_name='fcm',
            name='description',
            field=models.CharField(default='Test description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcm',
            name='map_html',
            field=models.FileField(default='media/images/one', upload_to='media/html'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcm',
            name='map_image',
            field=models.ImageField(default='media/images/two', upload_to='media/images'),
            preserve_default=False,
        ),
    ]
