# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0006_auto_20170910_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm',
            name='user',
        ),
    ]
