# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcm_app', '0007_remove_fcm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
