# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0008_fcm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM_CONCEPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fcmname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM')),
            ],
        ),
    ]
