# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0009_fcm_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM_CONCEPT_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('fcm_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM_CONCEPT')),
            ],
        ),
    ]
