# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0011_auto_20171025_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_concept',
            name='id_in_fcm',
            field=models.CharField(default='dummy', max_length=10),
            preserve_default=False,
        ),
    ]
