# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0012_fcm_concept_id_in_fcm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcm_concept',
            old_name='fcmname',
            new_name='fcm',
        ),
    ]
