# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 13:13
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0013_auto_20171110_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm',
            name='country',
            field=django_countries.fields.CountryField(default='GR', max_length=2),
            preserve_default=False,
        ),
    ]
