# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0014_fcm_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
