# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0015_fcm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
