# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0018_fcm_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM_MANUAL_CONCEPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('id_in_fcm_manual', models.CharField(max_length=10)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('fcm_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM_MANUAL')),
            ],
        ),
        migrations.CreateModel(
            name='FCM_MANUAL_EDGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('id_in_fcm_manual', models.CharField(max_length=10)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('fcm_manual_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM_MANUAL_CONCEPT')),
            ],
        ),
    ]
