# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0019_fcm_manual_concept_fcm_manual_edges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcm_manual_edges',
            old_name='x_position',
            new_name='from_node',
        ),
        migrations.RenameField(
            model_name='fcm_manual_edges',
            old_name='y_position',
            new_name='id_in_fcm_manual_edges',
        ),
        migrations.RemoveField(
            model_name='fcm_manual_concept',
            name='id_in_fcm_manual',
        ),
        migrations.RemoveField(
            model_name='fcm_manual_edges',
            name='id_in_fcm_manual',
        ),
        migrations.AddField(
            model_name='fcm_manual_concept',
            name='id_in_fcm_manual_concept',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fcm_manual_edges',
            name='to_node',
            field=models.IntegerField(default=0),
        ),
    ]
