# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0019_auto_20180622_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
