# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0020_auto_20180618_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM_EDGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('id_in_fcm_edges', models.CharField(max_length=10)),
                ('from_node', models.IntegerField(default=0)),
                ('to_node', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='fcm_manual',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fcm_manual_concept',
            name='fcm_manual',
        ),
        migrations.RemoveField(
            model_name='fcm_manual_edges',
            name='fcm_manual_concept',
        ),
        migrations.DeleteModel(
            name='mynew',
        ),
        migrations.AddField(
            model_name='fcm',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fcm_concept',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fcm_concept',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FCM_MANUAL',
        ),
        migrations.DeleteModel(
            name='FCM_MANUAL_CONCEPT',
        ),
        migrations.DeleteModel(
            name='FCM_MANUAL_EDGES',
        ),
        migrations.AddField(
            model_name='fcm_edges',
            name='fcm_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM_CONCEPT'),
        ),
    ]
