# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0023_auto_20180622_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm',
            name='map_image',
            field=models.ImageField(default='media/media/images/Capture1.PNG', upload_to='media/images'),
        ),
    ]
