# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0025_auto_20180622_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm',
            name='chartis',
            field=models.TextField(default=''),
        ),
    ]
