# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0026_fcm_chartis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm_edges',
            name='fcm_concept',
        ),
        migrations.AddField(
            model_name='fcm_edges',
            name='fcm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM'),
        ),
    ]
