# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0027_auto_20180721_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='fcm',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fcm_concept',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fcm_edges',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='fcm',
            name='tags',
            field=models.ManyToManyField(related_name='fcm_set', to='fcm_app.Tags'),
        ),
    ]
