# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 12:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0029_fcm_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM_EDGE_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FCM_EDGES_IN_FCM_CONCEPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('id_in_fcm', models.CharField(max_length=10)),
                ('fcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM')),
            ],
        ),
        migrations.AddField(
            model_name='fcm_edge_info',
            name='fcm_edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_app.FCM_EDGES_IN_FCM_CONCEPT'),
        ),
    ]
