# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0030_auto_20181012_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm_edges',
            name='fcm',
        ),
        migrations.DeleteModel(
            name='FCM_EDGES',
        ),
    ]
