# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0031_auto_20181012_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcm_edges_in_fcm_concept',
            name='title',
        ),
        migrations.AddField(
            model_name='fcm_edges_in_fcm_concept',
            name='from_concept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_concept', to='fcm_app.FCM_CONCEPT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcm_edges_in_fcm_concept',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fcm_edges_in_fcm_concept',
            name='to_concept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_concept', to='fcm_app.FCM_CONCEPT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcm_edges_in_fcm_concept',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
