# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0032_auto_20181012_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm_edges_in_fcm_concept',
            name='from_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_concept', to='fcm_app.FCM_CONCEPT'),
        ),
        migrations.AlterField(
            model_name='fcm_edges_in_fcm_concept',
            name='id_in_fcm',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fcm_edges_in_fcm_concept',
            name='to_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_concept', to='fcm_app.FCM_CONCEPT'),
        ),
    ]
