# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_app', '0033_auto_20181015_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm',
            name='original',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
